source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               lib/org.eclipse.jgit.jar,\
               lib/JavaEWAH.jar,\
               lib/slf4j-api.jar,\
               lib/commons-codec.jar
